import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { montserrat, poppins, robotoMono } from "./fonts";
import Providers from "@/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${poppins.variable} ${montserrat.variable} ${robotoMono.variable}`}
    >
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
