import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { montserrat, poppins, robotoMono } from "./fonts";
import Providers from "@/providers/Providers";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: ChildrenType) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html
        suppressHydrationWarning
        lang="en"
        className={`${poppins.variable} ${montserrat.variable} ${robotoMono.variable}`}
      >
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
